- menu_name: "Services"

- name: "Contact the ODC group"
  url: "/contacts/"
  title: "Contact the ODC group"

- name: "Legal mentions"
  url: "/ml/"
  title: "Legal mentions"

#- name: "RSS"
#  url: "/feed.xml"
#  title: "Subscribe to RSS Feed"

#- name: "Atom"
#  url: "/atom.xml"
#  title: "Subscribe to Atom Feed"

#- name: "sitemap.xml"
#  url: "/sitemap.xml"
#  title: "Sitemap for Google Webmaster Tools"
